tasks:
  - name: Set Rust version to working nightly
    command: rustup default nightly-2021-12-05
  - name: Install Rust tooling
    command: rustup component add rust-analysis rust-src rls clippy
  - name: Install entr
    command: sudo apt update && sudo apt install entr
vscode:
  extensions:
    - "swellaby.rust-pack"
